// This code was autogenerated with dbus-codegen-rust, see https://github.com/diwic/dbus-rs

#![allow(dead_code)]
use dbus as dbus;
use dbus::arg;
use dbus::tree;

pub trait ComCanonicalAppMenuRegistrar {
    type Err;
    fn register_window(&self, window_id: u32, menu_object_path: dbus::Path) -> Result<(), Self::Err>;
    fn unregister_window(&self, window_id: u32) -> Result<(), Self::Err>;
    fn get_menu_for_window(&self, window_id: u32) -> Result<(String, dbus::Path<'static>), Self::Err>;
    fn get_menus(&self) -> Result<Vec<(u32, String, dbus::Path<'static>)>, Self::Err>;
}

impl<'a, C: ::std::ops::Deref<Target=dbus::Connection>> ComCanonicalAppMenuRegistrar for dbus::ConnPath<'a, C> {
    type Err = dbus::Error;

    fn register_window(&self, window_id: u32, menu_object_path: dbus::Path) -> Result<(), Self::Err> {
        let mut m = try!(self.method_call_with_args(&"com.canonical.AppMenu.Registrar".into(), &"RegisterWindow".into(), |msg| {
            let mut i = arg::IterAppend::new(msg);
            i.append(window_id);
            i.append(menu_object_path);
        }));
        try!(m.as_result());
        Ok(())
    }

    fn unregister_window(&self, window_id: u32) -> Result<(), Self::Err> {
        let mut m = try!(self.method_call_with_args(&"com.canonical.AppMenu.Registrar".into(), &"UnregisterWindow".into(), |msg| {
            let mut i = arg::IterAppend::new(msg);
            i.append(window_id);
        }));
        try!(m.as_result());
        Ok(())
    }

    fn get_menu_for_window(&self, window_id: u32) -> Result<(String, dbus::Path<'static>), Self::Err> {
        let mut m = try!(self.method_call_with_args(&"com.canonical.AppMenu.Registrar".into(), &"GetMenuForWindow".into(), |msg| {
            let mut i = arg::IterAppend::new(msg);
            i.append(window_id);
        }));
        try!(m.as_result());
        let mut i = m.iter_init();
        let service: String = try!(i.read());
        let menu_object_path: dbus::Path<'static> = try!(i.read());
        Ok((service, menu_object_path))
    }

    fn get_menus(&self) -> Result<Vec<(u32, String, dbus::Path<'static>)>, Self::Err> {
        let mut m = try!(self.method_call_with_args(&"com.canonical.AppMenu.Registrar".into(), &"GetMenus".into(), |_| {
        }));
        try!(m.as_result());
        let mut i = m.iter_init();
        let menus: Vec<(u32, String, dbus::Path<'static>)> = try!(i.read());
        Ok(menus)
    }
}

pub fn com_canonical_app_menu_registrar_server<F, T, D>(factory: &tree::Factory<tree::MTFn<D>, D>, data: D::Interface, f: F) -> tree::Interface<tree::MTFn<D>, D>
where D: tree::DataType, D::Method: Default, T: ComCanonicalAppMenuRegistrar<Err=tree::MethodErr>,
    F: 'static + for <'z> Fn(& 'z tree::MethodInfo<tree::MTFn<D>, D>) -> & 'z T {
    let i = factory.interface("com.canonical.AppMenu.Registrar", data);
    let f = ::std::sync::Arc::new(f);
    let fclone = f.clone();
    let h = move |minfo: &tree::MethodInfo<tree::MTFn<D>, D>| {
        let mut i = minfo.msg.iter_init();
        let window_id: u32 = try!(i.read());
        let menu_object_path: dbus::Path = try!(i.read());
        let d = fclone(minfo);
        try!(d.register_window(window_id, menu_object_path));
        let rm = minfo.msg.method_return();
        Ok(vec!(rm))
    };
    let m = factory.method("RegisterWindow", Default::default(), h);
    let m = m.in_arg(("windowId", "u"));
    let m = m.in_arg(("menuObjectPath", "o"));
    let i = i.add_m(m);

    let fclone = f.clone();
    let h = move |minfo: &tree::MethodInfo<tree::MTFn<D>, D>| {
        let mut i = minfo.msg.iter_init();
        let window_id: u32 = try!(i.read());
        let d = fclone(minfo);
        try!(d.unregister_window(window_id));
        let rm = minfo.msg.method_return();
        Ok(vec!(rm))
    };
    let m = factory.method("UnregisterWindow", Default::default(), h);
    let m = m.in_arg(("windowId", "u"));
    let i = i.add_m(m);

    let fclone = f.clone();
    let h = move |minfo: &tree::MethodInfo<tree::MTFn<D>, D>| {
        let mut i = minfo.msg.iter_init();
        let window_id: u32 = try!(i.read());
        let d = fclone(minfo);
        let (service, menu_object_path) = try!(d.get_menu_for_window(window_id));
        let rm = minfo.msg.method_return();
        let rm = rm.append1(service);
        let rm = rm.append1(menu_object_path);
        Ok(vec!(rm))
    };
    let m = factory.method("GetMenuForWindow", Default::default(), h);
    let m = m.in_arg(("windowId", "u"));
    let m = m.out_arg(("service", "s"));
    let m = m.out_arg(("menuObjectPath", "o"));
    let i = i.add_m(m);

    let fclone = f.clone();
    let h = move |minfo: &tree::MethodInfo<tree::MTFn<D>, D>| {
        let d = fclone(minfo);
        let menus = try!(d.get_menus());
        let rm = minfo.msg.method_return();
        let rm = rm.append1(menus);
        Ok(vec!(rm))
    };
    let m = factory.method("GetMenus", Default::default(), h);
    let m = m.out_arg(("menus", "a(uso)"));
    let i = i.add_m(m);
    i
}

pub fn com_canonical_app_menu_registrar_window_registered_emit<C: ::std::ops::Deref<Target=dbus::Connection>>(conn: &dbus::ConnPath<C>, window_id: u32, service: String, menu_object_path: dbus::Path<'static>) -> Result<(), dbus::Error> {
    conn.signal_with_args(&"com.canonical.AppMenu.Registrar".into(), &"WindowRegistered".into(), move |msg| {
         let mut i = arg::IterAppend::new(msg);
         i.append(window_id);
         i.append(service);
         i.append(menu_object_path);
    }).map(|_| ())
}

pub fn com_canonical_app_menu_registrar_window_unregistered_emit<C: ::std::ops::Deref<Target=dbus::Connection>>(conn: &dbus::ConnPath<C>, window_id: u32) -> Result<(), dbus::Error> {
    conn.signal_with_args(&"com.canonical.AppMenu.Registrar".into(), &"WindowUnregistered".into(), move |msg| {
         let mut i = arg::IterAppend::new(msg);
         i.append(window_id);
    }).map(|_| ())
}
